# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk:
  #- jdk-12.0.2
  - jdk-12

#jdk:
#- jdk1.8.0_201
#jdk:
#- openjdk11

#Интеграция базы данных PostgreSQL и Travic CI
services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

# используем режим обычного пользователя для сборки проекта.
# это для того чтобы наш проект собирался быстрее
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - pimalex1978@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

# Ключ. Вы можете установить его в своих переменных окружения CI.
env:
  global:
    - CODECOV_TOKEN="3f3a3c3e-7e21-45c4-a8bc-a1e69530d497"

