# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

#jdk:
  #- openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -pimalex1978@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

# Ключ. Вы можете установить его в своих переменных окружения CI.
env:
  global:
    - CODECOV_TOKEN="3f3a3c3e-7e21-45c4-a8bc-a1e69530d497"

